= pyTigerGraph
:description: Overview of pyTigerGraph.

pyTigerGraph is a Python package for connecting to TigerGraph databases.
We offer two versions of the package: _pyTigerGraph_ and _pyTigerGraph[gds]_.

_pyTigerGraph_ is the default version and contains the core functionality of pyTigerGraph, which includes:

* Data manipulation functions: working with vertices and edges (insert/update/upsert, delete
  and retrieve)
* Query functions: running (and managing) queries (≈ stored procedures) inside the TigerGraph
  database
* Metadata functions: fetching details of graphs/schemas, vertex and edge types, and other
  schema objects and object types
* Authentication and authorization functions
* Miscellaneous/utility functions

The _pyTigerGraph[gds]_ version of pyTigerGraph is a drop-in replacement for _pyTigerGraph_,
but adds support for Graph Data Science and Graph machine learning capabilities.
This includes:

* Graph feature engineering using algorithms from the xref:graph-ml:intro:[GSQL Graph Data Science Library].
* Data loaders for training and inference of Graph Neural Network (GNN) models using PyTorch Geometric and DGL.
* Machine learning utilities for splitting vertices into training, validation, and testing sets.

== Getting Started
Checkout the xref:getting-started:index.adoc[Getting Started] section for a quick introduction to pyTigerGraph.
It contains instructions on how to install the package and connect to a TigerGraph database, as well as a few examples.

== pyTigerGraph Community
There are many community resources that you can use for help and support using pyTigerGraph:

* **TigerGraph Community Forum:** https://dev.tigergraph.com/forum/
* **TigerGraph Discord:** https://discord.gg/XM7Cn9w
* **pyTigerGraph GitHub Issues:** https://github.com/tigergraph/pyTigerGraph/issues

== Contributing
Checkout the xref:contributing:index.adoc[Contributing] section for instructions on how to contribute. pyTigerGraph was started as an open-source community project, and we welcome contributions from the community.