= pyTigerGraph
:description: Overview of pyTigerGraph.

pyTigerGraph is a Python package for connecting to TigerGraph databases.

*Already familiar with pyTigerGraph?* Join the xref:_pytigergraph_community[], else, get to know pyTigerGraph below.

== Get to Know pyTigerGraph
[.home-card,cols="2,2",grid=none,frame=none]
|===
a|
*Getting Started*

Checkout the xref:pytigergraph:getting-started:index.adoc[] section for a quick introduction to pyTigerGraph.
Or go hands on with our xref:pytigergraph:getting-started:101.adoc[] that walks you through all core functions of pyTigergraph:


a|
*Core Functions*

xref:pytigergraph:core-functions:index.adoc[]
allow you to use the  core features of the TigerGraph database through pyTigerGraph.

a|
*GDS Functions*

Graph Data Science xref:pytigergraph:gds:index.adoc[(GDS) Functions]  perform machine learning tasks.

a|
*Datasets*

xref:pytigergraph:datasets:datasets.adoc[] ingest stock datasets into a TigerGraph database.
a|
*Visualizations*

Use xref:visualization:visualization.adoc[] to visualize graphs.

a|
*Object-Oriented Schema*

The xref:object_oriented_schema:schema-def.adoc[] functionality allows users to manipulate schema elements in the database in an object-oriented approach in Python.

a|
*Contributing*

Checkout the xref:pytigergraph:contributing:index.adoc[] section for instructions on how to contribute.


a|
*Release Notes*

See xref:pytigergraph:release-notes:index.adoc[]
for the most up-to-date news on pyTigerGraph.

a|
|===

== pyTigerGraph Community
There are many community resources that you can use for help and support using pyTigerGraph:

* https://dev.tigergraph.com/forum/[TigerGraph Community Forum]
* https://discord.gg/XM7Cn9w[TigerGraph Community Discord]
* https://github.com/tigergraph/pyTigerGraph/issues[pyTigerGraph GitHub Issues]

== pyTigerGraph vs. pyTigerGraph[gds]
We offer two versions of the package: _pyTigerGraph_ and _pyTigerGraph[gds]_.

_pyTigerGraph_ is the default version and contains the core functionality of pyTigerGraph, including the following:

* Data manipulation functions:inserting, updating, upserting, deleting, and retrieving vertices and edges.
* Query functions: running and managing xref:gsql-ref:querying:query-operations.adoc[queries] inside the TigerGraph
database
* Metadata functions: fetching details of graphs/schemas, vertex and edge types, and other
schema objects and object types
* Authentication and authorization functions
* Miscellaneous utility functions

The _pyTigerGraph[gds]_ version of pyTigerGraph is a drop-in replacement for _pyTigerGraph_,
but adds support for Graph Data Science and Graph machine learning capabilities.
This includes:

* Graph feature engineering using algorithms from the xref:graph-ml:intro:[GSQL Graph Data Science Library].
* Data loaders for training and inference of Graph Neural Network (GNN) models using PyTorch Geometric and DGL.
* Machine learning utilities for splitting vertices into training, validation, and testing sets.
