= pyTigerGraph Connection

== Constructor
`__init__(host: str = "http://127.0.0.1", graphname: str = "MyGraph", username: str = "tigergraph", password: str = "tigergraph", restppPort: [int, str] = "9000", gsPort: [int, str] = "14240", gsqlVersion: str = "", version: str = "", apiToken: str = "", useCert: bool = True, certPath: str = None, debug: bool = False, sslPort: [int, str] = "443", gcp: bool = False)`

Initiate a connection object.

[discrete]
=== Parameters:
* `host`: The host name or IP address of the TigerGraph server.
* `graphname`: The default graph for running queries.
* `username`: The username on the TigerGraph server.
* `password`: The password for that user.
* `restppPort`: The port for REST++ queries.
* `gsPort`: The port of all other queries.
* `gsqlVersion`: The version of the GSQL client to be used. Effectively the version of the database
being connected to.
* `version`: DEPRECATED; use `gsqlVersion()`.
* `apiToken`: DEPRECATED; use `getToken()` with a secret to get a session token.
* `useCert`: DEPRECATED; the need for CA certificate is now determined by URL scheme.
* `certPath`: The filesystem path to the CA certificate. Required in case of https connections.
* `debug`: Enable debug messages.
* `sslPort`: Port for fetching SSL certificate in case of firewall.
* `gcp`: Is firewall used?

[discrete]
=== Raises:
TigerGraphException: In case on invalid URL scheme.



