= Getting Started

== Deploying _pyTigerGraph_ and _pyTigerGraph[gds]_

To download _pyTigerGraph_, simply run
[source:shell]
----
pip3 install pyTigerGraph
----
in the command line or use the appropriate tool of your development environment (anaconda, PyCharm, etc.).

Once the package is installed, you just import it:
[source:python]
----
import pyTigerGraph as tg
----

== Establishing the connection to a TigerGraph database
_pyTigerGraph_ connects to the TigerGraph database through various REST API endpoints. Some of
these endpoints use https://datatracker.ietf.org/doc/html/rfc7617[basic] (username/password)
based authentication, others use https://datatracker.ietf.org/doc/html/rfc6750[bearer token]
based authentication.

Therefore, to access a
https://docs.tigergraph.com/tigergraph-server/current/user-access/enabling-user-authentication[properly secured]
TigerGraph instance, you need to provide credentials for both authentication scheme.

* The username and password is provided via the constructor of the `TigerGraphConnection` class (see below).

* The token for the bearer authentication scheme is not provided directly. Instead, you need a
_https://docs.tigergraph.com/tigergraph-server/current/user-access/managing-credentials#_secrets[secret]_
that you will use to get a session token. Secrets are unique strings that serve as a user’s
credentials in certain circumstances. +
If there is a
(database) administrator looking after your TigerGraph instance, request a secret from them.
If you manage your own instance, you can https://docs.tigergraph.com/tigergraph-server/current/user-access/managing-credentials#_create_a_secret[generate the
 secret] yourself. +

In addition to these, you need to provide the hostname or IP address of the TigerGraph instance
and the name of a _graph_. The graph in this context is a logical container that consists of
object type (vertex and edge type, UDT, data sources, etc.) definitions and the instances of
these object types (i.e. the actual vertex and edge data, etc.). A graph in this sense is
equivalent of a schema in a relational database. A TigerGraph instance can contain a large
number of graphs, so you need to specify which one you want to use.

Establishing a connection requires these two statements:

[source:python]
----
conn = tg.TigerGraphConnection(host="<hostname>", graphname="<graph_name>", username="<username>", password="<password>")
conn.getToken(<secret>)
----

For example:

[source:python]
----
conn = tg.TigerGraphConnection("r_alliance.i.tgcloud.io", "GoodsDelivery", "hsolo", "f4lc0n")
conn.getToken('oodvd1upqbj96vq22jof21o8nl8cjkd5')
----

If your instance is not secure (i.e. user authentication is not enabled), then connecting to your
TigerGraph instance can be this simple:

[source:python]
----
conn = tg.TigerGraphConnection("r_alliance.i.tgcloud.io", "GoodsDelivery")
----

Or even this, if e.g. you are running locally a virtual machine or a container with port mapping and you
are using the default graph "MyGraph":

[source:python]
----
conn = tg.TigerGraphConnection()
----

For more connection options, see the complete parameter list of the xref:authentication:base.adoc[ constructor] of the `TigerGraphConnection` class.

Once you have established the connection you can start using pyTigerGraph, e.g.

[source:python]
----
veggies = conn.getVertices("products", where="category=vegetable"))

results = conn.runInstalledQuery("shortest_delivery", {"warehouse": 1234, "store": 5678})
----
