= Installing pyTigerGraph
:description: Instructions to install each flavor of pyTigerGraph.

This page walks you through installing pyTigerGraph on your machine.

== Prerequisites
* OS version
* Python version
* Package managers

== Install _pyTigerGraph_

To download _pyTigerGraph_, run the following command in the command line or use the appropriate tool of your development environment (anaconda, PyCharm, etc.).:

[source,console]
----
pip3 install pyTigerGraph
----

== Install _pyTigerGraph[gds]_

To utilize the Graph Data Science functionality in the xref:gds:index.adoc[GDS] section, download the GDS package that fits your needs.
Any of the options below allows you to use GDS functions, but certain flavors allow you to output results in formats sup
The options are:

* To install all required packages for full GDS functionality, including PyTorch, PyTorch Geometric, and DGL, run the following command:
+
----
pip3 install pyTigerGraph[gds]
----
* To use the GDS functions with the option of producing output in the format supported by the *PyTorch Geometric framework*, run the following command:
+
----
pip3 install pyTigerGraph[gds-pyg]
----
* To use the GDS functions with the option of producing output in the format supported by the Deep Graph Library (GDL) framework, run the following command:
+
----
pip3 install pyTigerGraph[gds-dgl]
----
* To use the GDS functions without needing to produce output in the format supported by PyTorch Geometric or DGL.
This makes the data loaders output Pandas dataframes:
+
----
pip3 install pyTigerGraph[gds-lite]
----

Once the package is installed, you can import it like any other Python package:

[source,python]
----
import pyTigerGraph as tg
----