= GSQL Interface


Use GSQL within pyTigerGraph.
All functions in this module are called as methods on a link:https://docs.tigergraph.com/pytigergraph/current/core-functions/base[`TigerGraphConnection` object]. 

== gsql()
`gsql(query: str, graphname: str = None, options = None) -> Union[str, dict]`

Runs a GSQL query and processes the output.

[discrete]
==== Parameters:
* `query`: The text of the query to run as one string. The query is one or more GSQL statement.
* `graphname`: The name of the graph to attach to. If not specified, the graph name provided at the
time of establishing the connection will be used.
* `options`: DEPRECATED

[discrete]
==== Returns:
The output of the statement(s) executed.


== installUDF()
`installUDF(ExprFunctions: str = "", ExprUtil: str = "") -> None`

Install User Defined Function (UDF) to the database.  +
See the https://docs.tigergraph.com/gsql-ref/current/querying/func/query-user-defined-functions[documentation] for more details. for details on UDFs.

[discrete]
==== Parameters:
ExprFunctions (str, optional): 
Path to the file for ExprFunctions. Defaults to ''.
ExprUtil (str, optional): 
Path to the file for ExprUtil. Defaults to ''.

[discrete]
==== Returns:
Status of the installation.


