== Loading Job Functions

=== runLoadingJobWithFile
`runLoadingJobWithFile(filePath: str, fileTag: str, jobName: str, sep: str = None, eol: str = None, timeout: int = 16000, sizeLimit: int = 128000000) -> dict`

Execute a loading job with the referenced file.

The file will first be uploaded to the tigergraph server and the value of the appropriate
FILENAME definition will be updated to point to the freshly uploaded file.

[discrete]
==== **Parameters:**
* `filePath`: File variable name or file path for the file containing the data.
* `fileTag`: The name of file variable in the loading job (DEFINE FILENAME <fileTag>).
* `jobName`: The name of the loading job.
* `sep`: Data value separator. If your data is JSON, you do not need to specify this
parameter. The default separator is a comma (,).
* `eol`: End-of-line character. Only one or two characters are allowed, except for the
special case "\r\n". The default value is "\n"
* `timeout`: Timeout in seconds. If set to 0, use the system-wide endpoint timeout setting.
* `sizeLimit`: Maximum size for input file in bytes.

[discrete]
==== **Endpoint:**
- `POST /ddl/{graph_name}`
 +
See the https://docs.tigergraph.com/tigergraph-server/current/api/built-in-endpoints#_run_a_loading_job[documentation] for more details.


=== uploadFile
`uploadFile(filePath, fileTag, jobName = "", sep = None, eol = None, timeout = 16000, sizeLimit = 128000000) -> dict`

DEPRECATED

Use `runLoadingJobWithFile()` instead.


