= User Defined Tuple (UDT) Functions


The functions on this page retrieve information about user-defined tuples (UDT) for the graph.
All functions in this module are called as methods on a link:https://docs.tigergraph.com/pytigergraph/current/core-functions/base[`TigerGraphConnection` object].

== getUDTs()
`getUDTs() -> list`

Returns the list of User-Defined Tuples (names only).

For information on UDTs, see the xref:gsql-ref:ddl-and-loading:attribute-data-types.adoc#user-defined-tuples[User-Defined Tuples] page of the GSQL language documentation.
[discrete]
==== Returns:
The list of names of UDTs (defined in the global scope, i.e. not in queries).


== getUDT()
`getUDT(udtName: str) -> list`

Returns the details of a specific User-Defined Tuple (defined in the global scope).

For information on UDTs, see the xref:gsql-ref:ddl-and-loading:attribute-data-types.adoc#user-defined-tuples[User-Defined Tuples] page of the GSQL language documentation.

[discrete]
==== Parameter:
* `udtName`: The name of the User-Defined Tuple.

[discrete]
==== Returns:
The metadata (the details of the fields) of the UDT.


