= Utility Functions


Utility functions for pyTigerGraph.
All functions in this module are called as methods on a link:https://docs.tigergraph.com/pytigergraph/current/core-functions/base[`TigerGraphConnection` obejct]. 

== echo()
`echo(usePost: bool = False) -> str`

Pings the database.

[discrete]
==== **Parameter:**
* `usePost`: Use POST instead of GET

[discrete]
==== **Returns:**
"Hello GSQL" if everything was OK.

[discrete]
==== **Endpoint:**
- `GET /echo`
- `POST /echo`
See xref:tigergraph-server:API:built-in-endpoints.adoc#_echo[Echo]



== getVersion()
`getVersion(raw: bool = False) -> Union[str, list]`

Retrieves the git versions of all components of the system.

[discrete]
==== **Parameter:**
* `raw`: Return unprocessed version info string, or extract version info for each component
into a list.

[discrete]
==== **Returns:**
Either an unprocessed string containing the version info details, or a list with version
info for each component.

[discrete]
==== **Endpoint:**
- `GET /version`
See xref:tigergraph-server:API:built-in-endpoints.adoc#_show_component_versions[Show component versions]


== getVer()
`getVer(component: str = "product", full: bool = False) -> str`

Gets the version information of a specific component.

Get the full list of components using `getVersion()`.

[discrete]
==== **Parameters:**
* `component`: One of TigerGraph's components (e.g. product, gpe, gse).
* `full`: Return the full version string (with timestamp, etc.) or just X.Y.Z.

[discrete]
==== **Returns:**
Version info for specified component.

[discrete]
==== **Raises:**
`TigerGraphException` if invalid/non-existent component is specified.


== getLicenseInfo()
`getLicenseInfo() -> dict`

Returns the expiration date and remaining days of the license.

[discrete]
==== **Returns:**
Returns license details. For an evaluation/trial deployment, returns an information message and -1 remaining days.



