= Featurizer

The Featurizer class provides methods for installing and running Graph Data Science Algorithms onto a TigerGraph server.

== \__init__()
`__init__(conn: TigerGraphConnection)`

Class for feature extraction.

The job of a feature extracter is to install and run algorithms in the Graph Data Science (GDS) libarary.
Currently, a set of graph algorithms are moved to the `gsql` folder, which you can find in the same directory as this file,
and have been saved into a dictionary along with their output type.
To add a specific algorithm, it should be added both to the `gsql` folder and class variable dictionary. 
[discrete]
==== **Parameter:**
conn (TigerGraphConnection): 
Connection to the TigerGraph database.


== listAlgorithms()
`listAlgorithms(category: str = None)`

Print the list of avalaible algorithms in GDS.
[discrete]
==== **Parameter:**
category (str): 
The class of the algorithms, if it is None the entire list will be printed out.


== installAlgorithm()
`installAlgorithm(query_name: str) -> str`

Checks if the query is already installed. If the query is not installed,
it installs the query and changes the schema if an attribute needs to be added.

[discrete]
==== **Parameter:**
query_name (str): 
The name of query to be installed


== runAlgorithm()
`runAlgorithm(query_name: str, params: dict = None, feat_name: str = None, schema_name: list = None, timeout: int = 2147480, sizeLimit: int = None) -> Any`

Runs an installed query.
The query must be already created and installed in the graph.
If the query accepts input parameters and the parameters have not been provided, calling this function runs the query with the default values for the parameters.
If the there isn't a default value in the query definition and no parameters are provided, the function raises a `ValueError`.

[discrete]
==== **Parameters:**
* `query_name (str)`: The name of the query to be executed.
* `params (dict)`: Query parameters. a dictionary.
feat_name (str): 
An attribute name that needs to be added to the vertex/edge
* `schema_name`: List of Vertices/Edges that the attr_name need to added to them.    
* `timeout (int)`: Maximum duration for successful query execution (in milliseconds).
* `sizeLimit (int)`: Maximum size of response (in bytes).

[discrete]
==== **Returns:**
The output of the query, a list of output elements (vertex sets, edge sets, variables,
accumulators, etc.


