= Featurizer

Runs and installs Graph Data Science Algorithms. Requires the authenticated user to have all `designer` privileges for full functionality. 

== Featurizer Functions


=== Constructor
`__init__(conn: TigerGraphConnection)`

Class for Feature Extraction.
The job of a feature extracter is to install and run algorithms in graph data science libarary.
Currently, a set of graph algorithms are moved to the `gsql` folder, which you can find in the same directory as this file,
and have been saved into a dictionary along with their output type.
To add a specific algorithm, it should be added both to the `gsql` folder and class variable dictionary. 
[discrete]
==== Parameters:
conn (TigerGraphConnection): Connection to the TigerGraph database.


=== installAlgorithm
`installAlgorithm(query_name: str, schema_type: str = "VERTEX", attr_name: str = None)`

Checks if the query is already installed. If the query is not installed,
it installs the query and changes the schema if an attribute needs to be added.

[discrete]
==== Parameters:s
query_name (str): 
the name of query to be installed
schema_type (str): 
vertex or edge 
attr_name (str): 
An attribute name that needs to be added to the vertex/edge


=== runAlgorithm
`runAlgorithm(name_of_query: str, params: dict = None, timeout: int = 2147480, sizeLimit: int = None)`

Runs an installed query.
The query must already be installed in the graph.
If the query accepts input parameters and the parammeters have not been provided, they will be initialized by parsing the query.
[discrete]
==== Parameters:s
* `name_of_query`: The name of the query to be executed.
* `params`: Query parameters. a dictionary.
* `timeout`: Timeout limit for successful query execution in milliseconds.
* `sizeLimit`: Maximum size of response in bytes.

[discrete]
==== Returns:
The output of the query, a list of output elements (vertex sets, edge sets, variables,
accumulators, etc.


