= Featurizer

The Featurizer class provides methods for installing and running Graph Data Science Algorithms onto a TigerGraph server.

== listAlgorithms()
`listAlgorithms(category: str = None)`

Print the list of avalaible algorithms in GDS.
[discrete]
==== **Parameter:**
category (str): 
The class of the algorithms, if it is None the entire list will be printed out.


== installAlgorithm()
`installAlgorithm(query_name: str) -> str`

Checks if the query is already installed, if not it will install the query and change the schema if an attribute needs to be added.        
[discrete]
==== **Parameter:**
query_name (str): 
The name of query to be installed


== runAlgorithm()
`runAlgorithm(query_name: str, params: dict = None, feat_name: str = None, schema_name: list = None, timeout: int = 2147480, sizeLimit: int = None) -> Any`

Runs an installed query.
The query must be already created and installed in the graph.
If the query accepts input parameters and the parameters have not been provided, they will be initialized by parsing the query.
If the initialized parameters contain any None value, the function will raise the ValueError.
[discrete]
==== **Parameters:**
* `query_name (str)`: The name of the query to be executed.
* `params (dict)`: Query parameters. a dictionary.
feat_name (str): 
An attribute name that needs to be added to the vertex/edge
* `schema_name`: List of Vertices/Edges that the attr_name need to added to them.    
* `timeout (int)`: Maximum duration for successful query execution (in milliseconds).
 +
See the https://docs.tigergraph.com/tigergraph-server/current/api/#_gsql_query_timeout[documentation] for more details.
* `sizeLimit (int)`: Maximum size of response (in bytes).
 +
See the https://docs.tigergraph.com/tigergraph-server/current/api/#_response_size[documentation] for more details.

[discrete]
==== **Returns:**
The output of the query, a list of output elements (vertex sets, edge sets, variables,
accumulators, etc.


