= Featurizer
Runs and installs Graph Data Science Algorithms. Requires `designer` user permissions for full functionality. 
See https://docs.tigergraph.com/tigergraph-server/current/user-access/access-control-model#_built_in_roles for more information.
== Featurizer Functions

=== Constructor
`__init__(conn: TigerGraphConnection)`

Class for Feature Extraction.
The job of a feature extracter is to install and run the current algorithms in graph data science libarary.
Currently, a set of graph algorithms are moved to the gsql folder and have been saved into a dictionary along with their output type.
To add a specific algorithm, it should be added both to the gsql folder and class variable dictionary. 
[discrete]
==== **Parameter:**
conn (TigerGraphConnection): Connection to the TigerGraph database.


=== installAlgorithm
`installAlgorithm(query_name: str, schema_type: str = "VERTEX", attr_name: str = None)`

Checks if the query is already installed, if not it will install the query and change the schema if an attribute needs to be added.
It can change 

[discrete]
==== **Parameters:**
query_name (str): 
the name of query to be installed
schema_type (str): 
vertex or edge 
attr_name (str): 
An attribute name that needs to be added to the vertex/edge


=== runAlgorithm
`runAlgorithm(name_of_query: str, params: dict = None, timeout: int = 2147480, sizeLimit: int = None)`

Runs an installed query.
The query must be already created and installed in the graph.
If the query accepts input parameters and the parammeters have not been provided, they will be initialized by parsing the query.
[discrete]
==== **Parameters:**
* `name_of_query`: The name of the query to be executed.
* `params`: Query parameters. a dictionary.
* `timeout`: Maximum duration for successful query execution (in milliseconds).
 +
See the https://docs.tigergraph.com/tigergraph-server/current/api/#_gsql_query_timeout[documentation] for more details.
* `sizeLimit`: Maximum size of response (in bytes).
 +
See the https://docs.tigergraph.com/tigergraph-server/current/api/#_response_size[documentation] for more details.

[discrete]
==== **Returns:**
The output of the query, a list of output elements (vertex sets, edge sets, variables,
accumulators, etc.


